require("cfg.main")
require("cfg.lazy")

require("plu.autopairs")
require("plu.autosave")
require("plu.blank-line")
require("plu.bufferline")
require("plu.cmake-tools")
require("plu.formatter")
require("plu.nvim_tree")
require("plu.lualine")
require("plu.notify")
require("plu.telescope")
require("plu.toggleterm")
require("plu.overseer")
require("plu.noice")
require("plu.which-key")
require("plu.inc-rename")
require("plu.cd-project")

require("plu.lsp.lsp")
require("plu.dap.total")
require("plu.mason.total")
require("plu.theme")

require("cfg.keymap")
