vim.keymap.set("i", "!exit", "<ESC>", { desc = "exit" })
vim.keymap.set("n", "<A-h>", "<CMD>BufferLineCyclePrev<CR>")
vim.keymap.set("n", "<A-l>", "<CMD>BufferLineCycleNext<CR>")
vim.keymap.set("n", "<LEADER>eo", "<CMD>Neotree<CR>")
vim.keymap.set("n", "<LEADER>ec", "<CMD>Neotree close<CR>")
vim.keymap.set("n", "<LEADER>format", "<CMD>Format<CR>")
vim.keymap.set("n", "<LEADER>action", "<CMD>Lspsaga code_action<CR>")
vim.keymap.set("n", "<LEADER>outline", "<CMD>Outline<CR>")
vim.keymap.set("n", "<LEADER>bd", "<CMD>bdelete %<CR>")
vim.keymap.set("n", "<LEADER>b!d", "<CMD>bdelete!<CR>")
vim.keymap.set("n", "<LEADER>dbp", "<CMD>lua require('dap').toggle_breakpoint()<CR>", { desc = "toggle_breakpoint" })
vim.keymap.set("n", "<LEADER>dc", "<CMD>lua require('dap').continue()<CR>", { desc = "continue" })
vim.keymap.set("n", "<LEADER>dso", "<CMD>lua require('dap').step_over()<CR>", { desc = "step_over" })
vim.keymap.set("n", "<LEADER>dsi", "<CMD>lua require('dap').step_into()<CR>", { desc = "step_into" })
vim.keymap.set("n", "<LEADER>dut", require("dapui").toggle, { desc = "toggle ui" })

